"""
update_progress.py
------------------
Run this before every git push.
Scans all phase folders, reads file timestamps, and auto-updates:
  - README.md     (progress badge — total problems pushed)
  - PROGRESS.md   (full problem log per phase)
  - CHANGELOG.md  (activity log grouped by date)
"""

import os
import re
from datetime import datetime, date
from pathlib import Path
from collections import defaultdict

# ── Config ────────────────────────────────────────────────────────────────────

BASE_DIR = Path(__file__).parent

PHASES = [
    {"folder": "python-basic-phase-1",      "name": "Phase 1 — Python Basics",               "range": "001–073"},
    {"folder": "python-intermediat-phase-2", "name": "Phase 2 — Intermediate Python",          "range": "074–146"},
    {"folder": "python-advance-phase-3",     "name": "Phase 3 — Advanced Python",              "range": "147–219"},
    {"folder": "python-dsa-phase-4",         "name": "Phase 4 — Data Structures & Algorithms", "range": "220–292"},
    {"folder": "python-core",                "name": "Phase 5 — Python Core & Internals",      "range": "293–365"},
]

TOTAL = 365

# ── Helpers ───────────────────────────────────────────────────────────────────

def get_files(folder: Path) -> list:
    if not folder.exists():
        return []
    files = []
    for f in sorted(folder.glob("*.py")):
        ts = f.stat().st_mtime
        added = datetime.fromtimestamp(ts)
        files.append({
            "name": f.name,
            "date": added.date(),
        })
    return files


def update_readme_badge(path: Path, completed: int):
    if not path.exists():
        print("  [skip] README.md not found")
        return
    content = path.read_text(encoding="utf-8")
    updated = re.sub(
        r"Progress-\d+%20%2F%20\d+",
        f"Progress-{completed}%20%2F%20{TOTAL}",
        content
    )
    # Also update the plain text "Completed: N" line
    updated = re.sub(
        r"\*\*Completed:\*\* \d+",
        f"**Completed:** {completed}",
        updated
    )
    if updated != content:
        path.write_text(updated, encoding="utf-8")
        print(f"  [updated] README.md  ->  {completed} / {TOTAL}")
    else:
        print(f"  [no change] README.md already at {completed} / {TOTAL}")


# ── PROGRESS.md ───────────────────────────────────────────────────────────────

def write_progress_md(phase_data: list, total: int):
    today = date.today().strftime("%B %d, %Y")
    last_activity = max(
        (f["date"] for p in phase_data for f in p["files"]),
        default="—"
    )

    lines = []
    lines.append("# Progress Log\n")
    lines.append(f"Last updated: {today}\n")
    lines.append("")

    # Summary table
    lines.append("## Summary\n")
    lines.append("| Metric | Value |")
    lines.append("|--------|-------|")
    lines.append(f"| Total Completed | {total} / {TOTAL} |")
    lines.append(f"| Phases Active | {sum(1 for p in phase_data if p['files'])} / {len(PHASES)} |")
    lines.append(f"| Last Push | {last_activity} |")
    lines.append("")

    # Phase breakdown
    lines.append("## Phase Breakdown\n")
    lines.append("| Phase | Folder | Completed | Problem Range |")
    lines.append("|-------|--------|-----------|---------------|")
    for p in phase_data:
        count = len(p["files"])
        lines.append(f"| {p['name']} | `{p['folder']}` | {count} | {p['range']} |")
    lines.append("")

    # Per-phase problem tables
    lines.append("## Problems by Phase\n")
    running = 0
    for p in phase_data:
        lines.append(f"### {p['name']}\n")
        lines.append(f"`{p['folder']}/` &nbsp;·&nbsp; Problems {p['range']}\n")
        if not p["files"]:
            lines.append("No problems pushed yet.\n")
            continue
        lines.append("| # | File | Date Pushed |")
        lines.append("|---|------|-------------|")
        for f in p["files"]:
            running += 1
            lines.append(f"| {running:03d} | `{f['name']}` | {f['date']} |")
        lines.append("")

    path = BASE_DIR / "PROGRESS.md"
    path.write_text("\n".join(lines), encoding="utf-8")
    print("  [done] PROGRESS.md")


# ── CHANGELOG.md ──────────────────────────────────────────────────────────────

def write_changelog_md(phase_data: list):
    by_date = defaultdict(list)
    for p in phase_data:
        for f in p["files"]:
            by_date[f["date"]].append({
                "file": f["name"],
                "phase": p["name"],
            })

    lines = []
    lines.append("# Changelog\n")
    lines.append("Auto-generated by `update_progress.py`. Updated on every push.\n")
    lines.append("")

    for d in sorted(by_date.keys(), reverse=True):
        count = len(by_date[d])
        lines.append(f"## {d.strftime('%B %d, %Y')} &nbsp;·&nbsp; {count} problem{'s' if count > 1 else ''}\n")
        for entry in by_date[d]:
            lines.append(f"- `{entry['file']}` &nbsp; {entry['phase']}")
        lines.append("")

    path = BASE_DIR / "CHANGELOG.md"
    path.write_text("\n".join(lines), encoding="utf-8")
    print("  [done] CHANGELOG.md")


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    print("\n=== update_progress.py ===\n")

    phase_data = []
    for phase in PHASES:
        files = get_files(BASE_DIR / phase["folder"])
        phase_data.append({**phase, "files": files})
        label = phase["folder"].ljust(35)
        print(f"  {label}  {len(files)} file(s)")

    total = sum(len(p["files"]) for p in phase_data)
    print(f"\n  Total: {total} / {TOTAL} problems\n")

    print("Updating README.md...")
    update_readme_badge(BASE_DIR / "README.md", total)

    print("Writing PROGRESS.md...")
    write_progress_md(phase_data, total)

    print("Writing CHANGELOG.md...")
    write_changelog_md(phase_data)

    print(f"\nDone. Now run:\n")
    print(f"  git add .")
    print(f"  git commit -m \"Day {total:03d} | Phase X | Your Topic\"")
    print(f"  git push origin main\n")


if __name__ == "__main__":
    main()
